import { LevelDefinition } from '../../domain/entities/level-definition';

/**
 * The 15 bundled levels, identical to the client's generated set (same
 * deterministic generator and seeds), so levels served remotely match the
 * shipped game. Multi-cell arrows are encoded via arrowId; walls block,
 * collectible stars award bonus points, and hard levels carry a time limit.
 */
export const BUNDLED_LEVEL_SEED: LevelDefinition[] = [
  new LevelDefinition(1, 'First Steps', 'EASY', 3, 3, [
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'RIGHT', arrowId: 2 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 4 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 6 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 8 },
  ]),
  new LevelDefinition(2, 'Warming Up', 'EASY', 3, 4, [
    { row: 1, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 3 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 5 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
    { row: 1, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 7 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 8 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 10 },
  ]),
  new LevelDefinition(3, 'Two Lanes', 'EASY', 4, 4, [
    { row: 2, col: 2, kind: 'ARROW', direction: 'RIGHT', arrowId: 1 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'RIGHT', arrowId: 1 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 2 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 3 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 3, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 1, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 8 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 9 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 10 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 11 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 12 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 13 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 14 },
  ]),
  new LevelDefinition(4, 'Wider Path', 'EASY', 4, 5, [
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 1, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 5 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 8 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 3, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 10 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 11 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 12 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 13 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 14 },
    { row: 1, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 15 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 17 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 18 },
  ]),
  new LevelDefinition(5, 'Full Square', 'EASY', 5, 5, [
    { row: 2, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 1 },
    { row: 4, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 3 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 3 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 5 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 6 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 9 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 10 },
    { row: 1, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 11 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 12 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 13 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 15 },
    { row: 3, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 15 },
    { row: 4, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 17 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 18 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 19 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 20 },
  ]),
  new LevelDefinition(6, 'Longer Arrows', 'MEDIUM', 5, 5, [
    { row: 3, col: 3, kind: 'WALL' },
    { row: 4, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 2 },
    { row: 4, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 3 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 4 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 5 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 6 },
    { row: 1, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 1, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 9 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 10 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 11 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 12 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 12 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 13 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
    { row: 3, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 15 },
    { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 17 },
    { row: 3, col: 2, kind: 'COLLECTIBLE' },
  ]),
  new LevelDefinition(7, 'Crossroads', 'MEDIUM', 5, 6, [
    { row: 3, col: 1, kind: 'WALL' },
    { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 1 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 1 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 1 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 3 },
    { row: 4, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 4 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 6 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 2, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 9 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 10 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 11 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 12 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 13 },
    { row: 1, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 14 },
    { row: 2, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 15 },
    { row: 0, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 16 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 17 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 18 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 19 },
    { row: 4, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 20 },
    { row: 4, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 21 },
    { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 22 },
    { row: 1, col: 3, kind: 'COLLECTIBLE' },
  ]),
  new LevelDefinition(8, 'Packed Grid', 'MEDIUM', 6, 6, [
    { row: 4, col: 2, kind: 'WALL' },
    { row: 3, col: 1, kind: 'WALL' },
    { row: 5, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
    { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 2, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 4 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 5 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 6 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 4, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 7 },
    { row: 1, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 8 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 10 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 11 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 12 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 13 },
    { row: 4, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 14 },
    { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 15 },
    { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 16 },
    { row: 2, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 17 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 17 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 18 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 19 },
    { row: 5, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 20 },
    { row: 4, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 20 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 21 },
    { row: 5, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 22 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 23 },
    { row: 5, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 24 },
    { row: 1, col: 3, kind: 'COLLECTIBLE' },
  ]),
  new LevelDefinition(9, 'Tight Fit', 'MEDIUM', 6, 6, [
    { row: 2, col: 4, kind: 'WALL' },
    { row: 2, col: 1, kind: 'WALL' },
    { row: 1, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 1 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 2 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 2 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 3 },
    { row: 5, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 4 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 5 },
    { row: 5, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
    { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 4, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 9 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 9 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 10 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 11 },
    { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 12 },
    { row: 3, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 12 },
    { row: 3, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 13 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 14 },
    { row: 2, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 15 },
    { row: 5, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
    { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 17 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 18 },
    { row: 5, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 19 },
    { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 20 },
    { row: 2, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 21 },
    { row: 1, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 22 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 23 },
    { row: 5, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 24 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 25 },
    { row: 1, col: 3, kind: 'COLLECTIBLE' },
    { row: 2, col: 2, kind: 'COLLECTIBLE' },
  ]),
  new LevelDefinition(10, 'Big Board', 'MEDIUM', 6, 7, [
    { row: 2, col: 5, kind: 'WALL' },
    { row: 2, col: 1, kind: 'WALL' },
    { row: 5, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
    { row: 4, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
    { row: 3, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
    { row: 2, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 2 },
    { row: 1, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 3 },
    { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
    { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 5 },
    { row: 3, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 6 },
    { row: 4, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
    { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 1, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 8 },
    { row: 0, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 1, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 9 },
    { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 10 },
    { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 11 },
    { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 11 },
    { row: 2, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 12 },
    { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 13 },
    { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 14 },
    { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 15 },
    { row: 3, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
    { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 17 },
    { row: 4, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 18 },
    { row: 5, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 19 },
    { row: 0, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 20 },
    { row: 5, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 21 },
    { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 22 },
    { row: 3, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 23 },
    { row: 5, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 24 },
    { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 25 },
    { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 26 },
    { row: 5, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 27 },
    { row: 2, col: 3, kind: 'COLLECTIBLE' },
    { row: 1, col: 3, kind: 'COLLECTIBLE' },
  ]),
  new LevelDefinition(
    11,
    'Long Hall',
    'HARD',
    7,
    6,
    [
      { row: 4, col: 2, kind: 'WALL' },
      { row: 2, col: 3, kind: 'WALL' },
      { row: 2, col: 1, kind: 'WALL' },
      { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
      { row: 3, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
      { row: 3, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
      { row: 4, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 2 },
      { row: 0, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 0, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 0, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
      { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 5 },
      { row: 6, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
      { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 7 },
      { row: 5, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 8 },
      { row: 5, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 8 },
      { row: 5, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 8 },
      { row: 4, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 9 },
      { row: 1, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 10 },
      { row: 1, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 10 },
      { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 11 },
      { row: 2, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 12 },
      { row: 6, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 13 },
      { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
      { row: 6, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 15 },
      { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 16 },
      { row: 0, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 17 },
      { row: 0, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 17 },
      { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 18 },
      { row: 1, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 19 },
      { row: 6, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 20 },
      { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 21 },
      { row: 6, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 22 },
      { row: 4, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 23 },
      { row: 6, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 24 },
      { row: 4, col: 4, kind: 'COLLECTIBLE' },
    ],
    120,
  ),
  new LevelDefinition(
    12,
    'Gridlock',
    'HARD',
    7,
    7,
    [
      { row: 5, col: 5, kind: 'WALL' },
      { row: 1, col: 3, kind: 'WALL' },
      { row: 2, col: 2, kind: 'WALL' },
      { row: 6, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 1 },
      { row: 6, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 1 },
      { row: 6, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 1 },
      { row: 4, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
      { row: 4, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 5, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
      { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 5 },
      { row: 4, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 6 },
      { row: 6, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 7 },
      { row: 5, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 7 },
      { row: 3, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 8 },
      { row: 3, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 8 },
      { row: 1, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 9 },
      { row: 6, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 10 },
      { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 11 },
      { row: 1, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 11 },
      { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 12 },
      { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 13 },
      { row: 1, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 13 },
      { row: 3, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 14 },
      { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 14 },
      { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 14 },
      { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 15 },
      { row: 4, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 15 },
      { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 16 },
      { row: 2, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 16 },
      { row: 1, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 17 },
      { row: 4, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 18 },
      { row: 2, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 19 },
      { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 20 },
      { row: 6, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 21 },
      { row: 6, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 22 },
      { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 23 },
      { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 24 },
      { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 24 },
      { row: 0, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 25 },
      { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 26 },
      { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 27 },
      { row: 5, col: 3, kind: 'COLLECTIBLE' },
    ],
    110,
  ),
  new LevelDefinition(
    13,
    'Tangled',
    'HARD',
    7,
    7,
    [
      { row: 3, col: 1, kind: 'WALL' },
      { row: 3, col: 5, kind: 'WALL' },
      { row: 3, col: 4, kind: 'WALL' },
      { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 1 },
      { row: 1, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 1 },
      { row: 2, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 1 },
      { row: 6, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 2 },
      { row: 2, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 3 },
      { row: 1, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
      { row: 4, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 5 },
      { row: 4, col: 3, kind: 'ARROW', direction: 'LEFT', arrowId: 5 },
      { row: 4, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
      { row: 4, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 7 },
      { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 8 },
      { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 9 },
      { row: 3, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 10 },
      { row: 6, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 11 },
      { row: 6, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 12 },
      { row: 1, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 13 },
      { row: 2, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 13 },
      { row: 6, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
      { row: 5, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 14 },
      { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 15 },
      { row: 0, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 16 },
      { row: 6, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 17 },
      { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 18 },
      { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 19 },
      { row: 1, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 19 },
      { row: 2, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 19 },
      { row: 3, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 20 },
      { row: 4, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 21 },
      { row: 2, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 22 },
      { row: 4, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 23 },
      { row: 6, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 24 },
      { row: 5, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 24 },
      { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 25 },
      { row: 2, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 26 },
      { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 27 },
      { row: 6, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 28 },
      { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 29 },
      { row: 2, col: 3, kind: 'COLLECTIBLE' },
      { row: 1, col: 1, kind: 'COLLECTIBLE' },
      { row: 1, col: 3, kind: 'COLLECTIBLE' },
    ],
    100,
  ),
  new LevelDefinition(
    14,
    'Sprawl',
    'HARD',
    7,
    8,
    [
      { row: 5, col: 1, kind: 'WALL' },
      { row: 3, col: 3, kind: 'WALL' },
      { row: 2, col: 2, kind: 'WALL' },
      { row: 1, col: 6, kind: 'WALL' },
      { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 1 },
      { row: 0, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 2 },
      { row: 4, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 3 },
      { row: 2, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 4 },
      { row: 3, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 4 },
      { row: 4, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 5 },
      { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 6 },
      { row: 5, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 7 },
      { row: 2, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 8 },
      { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 9 },
      { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 10 },
      { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 11 },
      { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 12 },
      { row: 2, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 13 },
      { row: 1, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 14 },
      { row: 3, col: 5, kind: 'ARROW', direction: 'RIGHT', arrowId: 15 },
      { row: 3, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 16 },
      { row: 6, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 17 },
      { row: 4, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 18 },
      { row: 6, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 19 },
      { row: 5, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 19 },
      { row: 4, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 20 },
      { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 21 },
      { row: 0, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 22 },
      { row: 1, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 23 },
      { row: 2, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 24 },
      { row: 6, col: 7, kind: 'ARROW', direction: 'DOWN', arrowId: 25 },
      { row: 5, col: 7, kind: 'ARROW', direction: 'DOWN', arrowId: 25 },
      { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 26 },
      { row: 6, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 27 },
      { row: 6, col: 0, kind: 'ARROW', direction: 'DOWN', arrowId: 28 },
      { row: 6, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 29 },
      { row: 2, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 30 },
      { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 31 },
      { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 32 },
      { row: 5, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 33 },
      { row: 3, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 34 },
      { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 35 },
      { row: 6, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 36 },
      { row: 1, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 37 },
      { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 38 },
      { row: 6, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 39 },
      { row: 3, col: 6, kind: 'COLLECTIBLE' },
      { row: 1, col: 3, kind: 'COLLECTIBLE' },
    ],
    90,
  ),
  new LevelDefinition(
    15,
    'The Great Escape',
    'HARD',
    8,
    8,
    [
      { row: 5, col: 4, kind: 'WALL' },
      { row: 5, col: 3, kind: 'WALL' },
      { row: 3, col: 1, kind: 'WALL' },
      { row: 2, col: 1, kind: 'WALL' },
      { row: 7, col: 6, kind: 'ARROW', direction: 'DOWN', arrowId: 1 },
      { row: 6, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 2 },
      { row: 4, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 4, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 3 },
      { row: 3, col: 4, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
      { row: 3, col: 3, kind: 'ARROW', direction: 'RIGHT', arrowId: 4 },
      { row: 2, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 5 },
      { row: 3, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 5 },
      { row: 2, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 6 },
      { row: 5, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 7 },
      { row: 4, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 7 },
      { row: 0, col: 4, kind: 'ARROW', direction: 'UP', arrowId: 8 },
      { row: 5, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 9 },
      { row: 5, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 10 },
      { row: 0, col: 1, kind: 'ARROW', direction: 'UP', arrowId: 11 },
      { row: 5, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 12 },
      { row: 4, col: 1, kind: 'ARROW', direction: 'LEFT', arrowId: 13 },
      { row: 5, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 14 },
      { row: 3, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 15 },
      { row: 3, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 15 },
      { row: 7, col: 7, kind: 'ARROW', direction: 'DOWN', arrowId: 16 },
      { row: 6, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 17 },
      { row: 7, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 18 },
      { row: 6, col: 3, kind: 'ARROW', direction: 'DOWN', arrowId: 18 },
      { row: 3, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 19 },
      { row: 0, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 20 },
      { row: 1, col: 5, kind: 'ARROW', direction: 'UP', arrowId: 20 },
      { row: 7, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 21 },
      { row: 2, col: 6, kind: 'ARROW', direction: 'RIGHT', arrowId: 22 },
      { row: 1, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 23 },
      { row: 2, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 23 },
      { row: 6, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 24 },
      { row: 0, col: 2, kind: 'ARROW', direction: 'UP', arrowId: 25 },
      { row: 0, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 26 },
      { row: 1, col: 6, kind: 'ARROW', direction: 'UP', arrowId: 26 },
      { row: 6, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 27 },
      { row: 4, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 28 },
      { row: 7, col: 1, kind: 'ARROW', direction: 'DOWN', arrowId: 29 },
      { row: 0, col: 3, kind: 'ARROW', direction: 'UP', arrowId: 30 },
      { row: 7, col: 5, kind: 'ARROW', direction: 'DOWN', arrowId: 31 },
      { row: 6, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 32 },
      { row: 3, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 33 },
      { row: 1, col: 2, kind: 'ARROW', direction: 'LEFT', arrowId: 34 },
      { row: 2, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 35 },
      { row: 1, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 36 },
      { row: 7, col: 4, kind: 'ARROW', direction: 'DOWN', arrowId: 37 },
      { row: 0, col: 7, kind: 'ARROW', direction: 'RIGHT', arrowId: 38 },
      { row: 0, col: 0, kind: 'ARROW', direction: 'UP', arrowId: 39 },
      { row: 1, col: 0, kind: 'ARROW', direction: 'LEFT', arrowId: 40 },
      { row: 7, col: 2, kind: 'ARROW', direction: 'DOWN', arrowId: 41 },
      { row: 6, col: 2, kind: 'COLLECTIBLE' },
      { row: 1, col: 1, kind: 'COLLECTIBLE' },
      { row: 2, col: 2, kind: 'COLLECTIBLE' },
    ],
    80,
  ),
];
